apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    upsource: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      upsource: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        upsource: frontend
        jetbrains.network/upsource: "true"
    spec:
      containers:
        - name: frontend
          args:
            - --J
          env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_NATIVE_TRANSPORT_PORT
              value: "9042"
            - name: UPSOURCE_DATABASE
              value: datastax
            - name: UPSOURCE_SERVICE_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: UPSOURCE_SERVICE_MESSAGING_PORT
              value: "10061"
            - name: UPSOURCE_STATISTICS_UPLOAD
              value: "true"
            - name: UPSOURCE_WEB_SERVER_LISTEN_PORT
              value: "10070"
            - name: UPSOURCE_SERVICE_ID
              value: "b83462d9-7693-49a2-96da-cd16a2769e1d"
            - name: UPSOURCE_SERVICE_SECRET
              value: "BUKQgV4QFlOq"
            - name: HUB_URL
              value: "http://hub:8080"
          image: jetbrains/upsource-frontend:2020.1.1815
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: frontend-logs
              mountPath: /opt/upsource-frontend/logs
      restartPolicy: Always
      volumes:
        - name: frontend-logs
          emptyDir: { }