apiVersion: apps/v1
kind: Deployment
metadata:
  name: psi-agent
  labels:
    upsource: psi-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      upsource: psi-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        upsource: psi-agent
        jetbrains.network/upsource: "true"
    spec:
      containers:
        - name: psi-agent
          args:
            - --J
          env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_NATIVE_TRANSPORT_PORT
              value: "9042"
            - name: UPSOURCE_DATABASE
              value: datastax
            - name: UPSOURCE_PSI_BROKER_HOST
              value: psi-broker
            - name: UPSOURCE_PSI_BROKER_LISTEN_PORT
            - name: UPSOURCE_SERVICE_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: UPSOURCE_SERVICE_MESSAGING_PORT
              value: "10061"
            - name: UPSOURCE_STATISTICS_UPLOAD
              value: "true"
            - name: UPSOURCE_SERVICE_ID
              value: "e697239b-b43c-4826-bb65-7f925deccc36"
            - name: UPSOURCE_SERVICE_SECRET
              value: "ut6ZQznZlALY"
          image: jetbrains/upsource-psi-agent:2020.1.1815
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: psi-agent-logs
              mountPath: /opt/upsource-psi-agent/logs
      restartPolicy: Always
      volumes:
        - name: psi-agent-logs
          emptyDir: { }